name: Infrastructure

on:
  push:
    branches:
      - $default-branch
    paths-ignore:
      - ".github/**.yml"
      - "!.github/workflows/terraform.yml"
      - "**.md"
      - ".gitignore"
  pull_request:
    branches:
      - $default-branch
    paths-ignore:
      - ".github/**.yml"
      - "!.github/workflows/terraform.yml"
      - "**.md"
      - ".gitignore"

concurrency: infrastructure-${{ github.ref }}

jobs:
  Plan:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Restore cache
        id: restore
        uses: actions/cache@v3
        with:
          path: |
            **/.terraform/
            **/.terraform.lock.hcl
          key: terraform-${{ github.sha }}

      - name: Plan
        uses: SanthoshNath/terraform-plan@v1
        with:
          working_directory: infra
          skip_init: ${{ steps.restore.outputs.cache-hit }}

  Apply:
    runs-on: ubuntu-latest
    needs: Plan
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Restore cache
        id: restore
        uses: actions/cache@v3
        with:
          path: |
            **/.terraform/
            **/.terraform.lock.hcl
          key: terraform-${{ github.sha }}

      - name: Init
        if: steps.restore.outputs.cache-hit != 'true'
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve -input=false
